name: Testing
on: push


jobs:
  test_project:
  runs-on: ubuntu-latest
  steps:
  - uses: action/checkout@v2
  - name: Run Django unit test
    run:
      pip3 install --user django
      cd cs50.harvard.edu/python/django/airline0/
      python3 manage.py test